Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "docker"
  config.vm.network "public_network"
  config.vm.provision "shell", path: "provision.sh"
  
  # Increase Memory to 2G
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
end
