Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define "master" do |master|
    master.vm.network "private_network", ip: "192.168.99.200"
    master.vm.hostname = "master.example.com"
  end

  config.vm.define "minion" do |minion|
    minion.vm.network "private_network", ip: "192.168.99.201"
    minion.vm.hostname = "minion.example.com"
  end

end
